import { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { Navbar } from '@/components/shared/Navbar';

const roboto = Roboto({
	weight: ['100', '300', '400', '500', '700', '900'],
	variable: '--font-primary',
	display: 'swap',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={`${roboto.variable}`}>
				<Navbar />
				{children}
			</body>
		</html>
	);
}
